repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
    - id: check-docstring-first
    - id: check-added-large-files
    - id: check-yaml
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
    - id: black
      language_version: python3
